name: get_state
description: state management package based on dependency injection, use the MVVM pattern.(rename from ca_presentation)
version: 3.6.0
auth: Hu Wenatao <hu.wentao@outlook.com>
homepage: https://github.com/Hu-Wentao
repository: https://github.com/Hu-Wentao/get_state


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  get_arch_core: '>=0.6.1 <2.0.0'
  get_arch_core:
    path: D:/flutter_arch/get_arch_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
